n = int(input('Digite um numero inteiro: '))
print('Sua tabuada:\n')
print('1 x {} = {}\n'.format(n, n*1))
print('2 x {} = {}\n'.format(n, n*2))
print('3 x {} = {}\n'.format(n, n*3))
print('4 x {} = {}\n'.format(n, n*4))
print('5 x {} = {}\n'.format(n, n*5))
print('6 x {} = {}\n'.format(n, n*6))
print('7 x {} = {}\n'.format(n, n*7))
print('8 x {} = {}\n'.format(n, n*8))
print('9 x {} = {}\n'.format(n, n*9))
print('10 x {} = {}\n'.format(n, n*10))
